from django.urls import path, include, re_path
from property_register_app import views

urlpatterns = [
    path('auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
    # path('subdivision/', views.SubdivisionList.as_view(), name='sub_list'),
    path('subdivision/<int:pk>/', views.SubdivisionRetrieveAPIView.as_view(), name = 'sub_view'),
    # path('subdivision_create/', views.SubdivisionCreateView.as_view(), name = 'sub_create'),
    # path('subdivision/<int:pk>/update/', views.SubdivisionUpdateView.as_view(), name = 'sub_update'),
    # path('subdivision/<int:pk>/delete/', views.SubdivisionDeleteView.as_view(), name = 'sub_delete'),
    path('classrooms/<int:id_subd>/', views.ClassesASubdivision.as_view(), name = 'class_list'),
    #path('classroom/<int:pk>/', views.ClassroomRetrieveAPIView.as_view(), name = 'class_view'),
    path('classroom/<int:id_class>/', views.ClassroomAPIView.as_view(), name = 'emp_in_cls'),
    # path('classroom_create/', views.ClassroomCreateView.as_view(), name='class_create'),
    # path('classrooms_all/', views.ClassroomAllView.as_view(), name = 'class_all'),
    # path('classroom/<int:pk>/update', views.ClassroomUpdateView.as_view(), name='class_up'),
    # path('classroom/<int:pk>/delete', views.ClassroomDeleteView.as_view(), name='class_del'),
    path('property/<int:id_un>/', views.PropertyAPIView.as_view()),
    path('subdivisions/', views.SubdivisionAPIView.as_view(), name='sub_api'),
    path('subdivisions/create/', views.SubdivisionAPICreateView.as_view(), name='sub_api_create'),
    path('subdivisions/delete/<int:pk>/', views.SubdivisionDestroyAPIView.as_view()),
    path('subdivisions/update/<int:pk>/', views.SubdivisionUpdateAPIView.as_view()),
    path('classroom/', views.ClassroomListAPIView.as_view(), name='class_api'),
    path('employees/', views.EmployeesAPIView.as_view(), name='employee_api'),
    path('property/', views.UnitOfPropertyAPIView.as_view(), name='property_api'),
    path('property/create/', views.UnitOfPropertyCreateApiView.as_view(), name='property_api_create'),
    path('employees/create/', views.EmployeeCreateAPIView.as_view(), name='employee_api_create'),
    path('classroom/create/', views.ClassroomCreateAPIView.as_view(), name='class_api_create'),
    path('classroom/update/<int:pk>/', views.ClassroomUpdateAPIView.as_view()),
    path('classroom/delete/<int:pk>/', views.ClassroomDeleteAPIView.as_view()),
    path('property_liab/create/', views.PropertyLiabilityCreateAPIView.as_view(), name='prop_liab_create'),
    path('property_liab/<int:pk>/', views.PropertyLiabilityRetrieveAPIView.as_view(), name='prop_liab'),
    path('property_liab/update/<int:pk>/', views.PropertyLiabilityUpdateAPIView.as_view()),
    path('property_liab/delete/<int:pk>/', views.PropertyLiabilityDeleteAPIView.as_view()),
    path('property_list/create/', views.PropertyListCreateAPIView.as_view(), name='prop_list_create'),
    path('property_list/update/<int:pk>/', views.PropertyListUpdateAPIView.as_view()),
    path('property_list/delete/<int:pk>/', views.PropertyListDeleteAPIView.as_view()),
    path('employee/<int:id_employee>/', views.EmployeeAPIView.as_view(), name='empl_api'),
    path('employee/update/<int:pk>/', views.EmloyeeUpdateAPIView.as_view()),
    path('employee/delete/<int:pk>/', views.EmloyeeDeleteAPIView.as_view()),
    path('search/<str:search_string>/', views.SearchAPIView.as_view()),
    path('property_list/<int:pk>/', views.PropertyListRetrieveAPIVew.as_view()),
    path('property/update/<int:pk>/', views.UnitOfPropertyUpdateAPIView.as_view()),
    path('property/delete/<int:pk>/', views.UnitOfPropertyDeleteAPIView.as_view()),
]