# Generated by Django 3.1.6 on 2021-04-04 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_register_app', '0002_auto_20210404_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='id_subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_register_app.subdivision'),
        ),
    ]
