# Generated by Django 3.1.6 on 2021-04-07 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_register_app', '0003_auto_20210404_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_liability',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property_register_app.classroom'),
        ),
        migrations.AlterField(
            model_name='property_list',
            name='date_of_creation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
