# Generated by Django 3.1.6 on 2021-04-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_register_app', '0004_auto_20210407_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_liability',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
